name: Packer Consul Linode

on:
  push:
    branches: [main]
  pull_request: 
    branches: [main]
    types: [opened, synchronize]

jobs:
  Validate-Packer:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Validate-Packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Template
        uses: jveraduran/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: packer/packer.json.pkr.hcl
  
  Format-Packer:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    name: Format-Packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Validate Template
        uses: jveraduran/packer-github-actions@master
        with:
          command: fmt
          target: packer/packer.json.pkr.hcl

  Build:
    needs: [Validate-Packer,Format-Packer]
    if: ${{ (github.event_name == 'release') && always() }}
    runs-on: ubuntu-latest
    name: Build
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      
      - name: Download Packer Plugin
        uses: jveraduran/packer-github-actions@master
        with:
          command: init
          target: packer/packer.json.pkr.hcl

      - name: Build Artifact
        uses: jveraduran/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort -force -var version=${{ github.run_number }}"
          target: packer/packer.json.pkr.hcl
        env:
          LINODE_TOKEN: ${{ secrets.LINODE_TOKEN }}

        